# Generated by Django 5.0.3 on 2024-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_carlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
