# Generated by Django 5.0.3 on 2024-03-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_alter_carlisting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlisting',
            old_name='id',
            new_name='car_id',
        ),
    ]
