# Generated by Django 5.0.2 on 2024-03-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_rename_id_carlisting_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'automatic'), ('Manual', 'manual')], max_length=20),
        ),
    ]
