# Generated by Django 5.0.2 on 2024-04-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0012_alter_rentalbooking_drop_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='drop_contact',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='drop_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='drop_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='pick_contact',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='pick_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='pick_time',
            field=models.TimeField(),
        ),
    ]
