# Generated by Django 5.0.2 on 2024-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0013_alter_rentalbooking_drop_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='owner',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
