# Generated by Django 5.0.2 on 2024-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0014_carlisting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
