# Generated by Django 5.0.2 on 2024-04-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0017_remove_carlisting_owner_rentalbooking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
