# Generated by Django 5.0.2 on 2024-04-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0020_feedback_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='rating',
        ),
    ]
