# Generated by Django 5.0.3 on 2024-04-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0021_remove_carlisting_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='car_id',
            field=models.IntegerField(null=True),
        ),
    ]
