# Generated by Django 5.0.2 on 2024-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0023_feedback_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
