# Generated by Django 5.0.2 on 2024-04-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0024_feedback_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
