# Generated by Django 5.0.2 on 2024-05-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0025_feedback_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='returned',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
