# Generated by Django 5.0.2 on 2024-05-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0026_remove_feedback_returned_alter_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
