# Generated by Django 5.0.2 on 2024-05-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0027_carlisting_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='daily_rate',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='make',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='model_year',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='transmission',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
