# Generated by Django 5.0.2 on 2024-05-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0028_alter_carlisting_daily_rate_alter_carlisting_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbooking',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
