# Generated by Django 5.0.2 on 2024-05-01 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0029_rentalbooking_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
