# Generated by Django 5.0.2 on 2024-05-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0030_alter_rentalbooking_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
