# Generated by Django 5.0.2 on 2024-05-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0031_alter_feedback_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
